# Update your shopify.app.toml file with Azure URLs:

client_id = "67ffaa64217a1b4557a9cd7d70729833"
name = "meta data editor"
handle = "meta-data-editor-1"
application_url = "https://meta-data-editor-app.azurewebsites.net"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = [ "app/scopes_update" ]
uri = "/webhooks/app/scopes_update"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
uri = "/webhooks/gdpr"

[access_scopes]
scopes = "write_products,read_products"

[auth]
redirect_urls = [
  "https://meta-data-editor-app.azurewebsites.net/auth/callback", 
  "https://meta-data-editor-app.azurewebsites.net/auth/shopify/callback", 
  "https://meta-data-editor-app.azurewebsites.net/api/auth/callback"
]

[pos]
embedded = false