name: Build and Deploy Node.js App to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: 'Set up Node.js version'
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: 'Install All Dependencies'
        run: npm ci
      
      - name: 'Build the Application'
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: 'Prune Dev Dependencies'
        run: npm prune --production

      - name: 'Run Database Migrations'
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'meta-data-editor-shopify-rg'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
          startup-command: 'npm run start' # <-- ADD THIS LINE
